NewsSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from NewsSiteApp.views import redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('NewsSiteApp.urls')),
    path('', redirect_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

NewsSiteApp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.NewsList.as_view(), name='home'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='news_detail'),
    path('create/', views.NewsCreateView.as_view(), name='news_create'),
]

NewsSiteApp/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.TextField(max_length=200)
    publication_date = models.DateTimeField('Date Published')
    body_text = models.TextField('Body')
    image = models.ImageField(upload_to='news', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'pk': self.pk})

NewsSiteApp/forms.py
from django import forms

from .models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'publication_date', 'body_text', 'image')

NewsSiteApp/views.py
from django.views import generic
from .forms import NewsForm
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from .models import News


def redirect_view(request):
    response = redirect('news/')
    return response


class NewsList(generic.ListView):
    queryset = News.objects.get_queryset().order_by('id')
    template_name = 'home.html'
    paginate_by = 10

    def get_paginate_by(self, queryset):
        self.paginate_by = self.request.GET.get('paginate_by', self.paginate_by)
        return self.paginate_by


class NewsDetail(generic.DetailView):
    model = News
    template_name = 'news_detail.html'


class NewsCreateView(CreateView):
    template_name = 'create.html'
    form_class = NewsForm

NewsSiteApp/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Новостной портал</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous"/>
</head>

<body>
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #865622;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }
</style>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Новости</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock content %}
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center">Copyright &copy; Новостной портал 2021</p>
</footer>
</body>
</html>

NewsSiteApp/templates/create.html
{% extends 'base.html' %}

{% block content %}
    <div style="margin-left:20px;">
    <form action="" method="post" enctype="multipart/form-data">
        <h1>Создание новости</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать"/>
    </form>
    </div>
{% endblock content %}

NewsSiteApp/templates/home.html
{% extends "base.html" %}
{% block content %}
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
        }

        .head_text {
            color: white;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }

        .paginator {
            margin-left: 100px;
            margin-right: auto;
        }
    </style>

    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Добро пожаловать на новостной портал!</h3>
                        <p class="text-light">Все самые свежие новости тут
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
                {% for news in news_list %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ news.title }}</h2>
                            <p class=""><img src="{{ news.image.url }}"></p>
                            <p class="card-text text-muted h6">{{ news.publication_date }} </p>
                            <p class="card-text">{{ news.body_text }}</p>
                            <a href="{% url 'news_detail' news.id %}" class="btn btn-warning">Читать далее &rarr;</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
            <form method="get">
                <select id="input-limit" name="paginate_by" class="form-control">
                <option value="10" selected="selected">10</option>
                <option value="20">20</option>
                <option value="50">50</option>
                </select>
                <button type="submit">Количество новостей</button>
            </form>
            <div class="paginator">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Первая</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

NewsSiteApp/templates/news_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ news.title }} {% endblock title %}</h1>
        <p class=""><img src="{{ news.image.url }}"></p>
        <p class=" text-muted">{{ news.publication_date }}</p>
        <p class="card-text ">{{ news.body_text }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

NewsSiteApp/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">Создание новости</h5>
    <div class="card-body">
        <p class="card-text">Чтобы создать новость нажмите:</p>
        <a href="{% url 'news_create' %}"
           class="btn btn-danger">Нажми здесь</a>
    </div>
</div>
</div>

{% endblock sidebar %}